export const siteMetadata = {
  title: 'Harsh Singh',
  author: 'Harsh Singh',
  headerTitle: 'Harsh Singh',
  description: 'Undergraduate Computer Science student',
  language: 'en-us',
  theme: 'dark', // system, dark or light
  siteUrl: 'https://harsh-singh.vercel.app/',
  siteRepo: 'https://https://github.com/harshsingh1112',
  siteLogo: 'public/static/images/logo.png',
  image: '/static/images/avatar.jpeg',
  socialBanner: '/static/images/twitter-card.png',
  email: 'harshsingh34418@gmail.com',
  github: 'https://github.com/harshsingh1112',
  twitter: 'https://x.com/darkisticharsh',
  facebook: 'https://www.facebook.com/darkisticharsh/',
  linkedin: 'https://www.linkedin.com/in/harshsingh11/',
  spotify: 'https://open.spotify.com/user/gggs0o82iaqoy2le3pd0l49rh?si=1fd1566b6a734369',
  locale: 'en-US',
};
